import Footer from './components/Footer/Footer'
import Header from './components/Header/Header'
import { FrontProvider } from './contexts/providers/FrontProvider'
import './style.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <FrontProvider>
          <Header></Header>
            {children}
          <Footer></Footer>
        </FrontProvider>
      </body>
    </html>
  )
}
